module.exports = {
    List:'Name Of List',
    List1:'Apple',
    List2:'mango',
    List3:'Grapes', 
    Birthday : 'Birthday' ,
    Hour:'11',
    Minute:'30',
    sorting:"alphabetically",
    Name:'Aman Birthday',
    text:"Calendar",
    date:"20",
    add:"Add",
    text1:"Text",
    textDailog:"Add note [Thu, May 19]",
    listName:"note",
    Details:"Hi i m sukhjeet kaur!!!!!",
    addItem:"Add Item",
    Button:"OK",
    find:"Find",
    verifyText:"Awesome!",
    gender:"Female",
    nameField:"What is your Name?",
    verifyNameText:"Name",
    nameText:"sukhjeet",
    date:"21",
    location:"What is your Home Location/City?",
    locationText:"100 Feet Hospital",
    born:"When were you born?",
    homeText:"Parindey",
    searchTabText:"Explore",
    searchNameText:"Devika ",
    button1:"FOLLOW",
    button2:"MESSAGE",
    MessageText:"Smile & Say Hi!",
    enterFiledText:"Enter message",
    errorMessText:"Please Enter Your Name",
    errorMessBirthday:"Please Enter Your Birthdate",
    errorMessLocation:"Please Enter Your Home / City Location"
	
  
, timeOut: '3000'
}